import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>dlw Horizontal Slider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center items-center antialiased font-sans text-gray-200 bg-gray-900 ">
        <div className="text-lg max-w-prose mx-auto">
          <main>
            <h1 className="text-3xl font-bold underline text-pink-600">
              Hello world!
            </h1>
          </main>
        </div>
      </div>
    </>
  )
}
